### ISSUE TITLE
Integrate with parsnip

### ISSUE THREAD

**Issue by zenggyu** [tidymodels/tidypredict#48]
Currently `tidypredict` only works with model objects trained by the original packages (`randomForest`, `glm`, etc.), but it does not work with model objects trained by `parsnip`. Since `tidypredict` is part of `tidymodels`, I think eventually `tidypredict` should be able to translate `parsnip` model objects. Perhaps this is too early since `parsnip` is not stable yet, but here is the issue anyway.

**Comment by topepo** [comment]
We can implement `tidypredict` engines for `parsnip`. The main bottleneck is writing `tidypredict_fit` methods for the underlying models; that's where all of the work is. 

There are some models (KNN, SVM's, etc) that are infeasible to use with `tidypredict` since they would store all, or some fraction, of the training set.

**Comment by edgararuiz** [comment]
Fixed with c322ce782d99ba68e913cf976a9a8a74516a9287

**Comment by edgararuiz** [comment]
Thanks @zenggyu for your suggestion, I have the interface working and my tests were successful, please let me know if you find anything.
